### ISSUE TITLE
Dependencies error in LogExceptionListener

### ISSUE THREAD

**Issue by maximecolin** [BedrockStreaming/LogBridgeBundle#53]
I bumped into a bug in the [LogExceptionListener](https://github.com/M6Web/LogBridgeBundle/blob/master/src/M6Web/Bundle/LogBridgeBundle/EventDispatcher/LogExceptionListener.php).

I don't know yet why but in my case, `setLogger` and `setMatcher` are not called so `$logger` and `$matcher` are null resulting in an error when `onKernelTerminate` try to use them.

**First point:**

I don't understand why these dependencies are set with a method call in [M6WebLogBridgeExtension](https://github.com/M6Web/LogBridgeBundle/blob/master/src/M6Web/Bundle/LogBridgeBundle/DependencyInjection/M6WebLogBridgeExtension.php#L72-L82) instead of being injected in the constructor. They seems to be mandatory dependencies, so they should be in the injected in the constructor.

**Second point:**

If we keep the methods calls, we should either add a condition to skip [this part of the code](https://github.com/M6Web/LogBridgeBundle/blob/master/src/M6Web/Bundle/LogBridgeBundle/EventDispatcher/LogRequestListener.php#L55-L63) or throw an exception if these variables are null depending if these dependencies are optional or not.

Can you tell me if these dependencies are optional or not and which solutions I should use to fix ?

**Comment by maximecolin** [comment]
It appears both logger and matcher are injected through `M6WebLogBridgeExtension::loadExceptionListener` method when `$config['exception']['log']` is true. So these dependencies are definitely optional and [M6WebLogBridgeExtension](https://github.com/M6Web/LogBridgeBundle/blob/master/src/M6Web/Bundle/LogBridgeBundle/DependencyInjection/M6WebLogBridgeExtension.php#L72-L82) should be conditioned

**Comment by klobermajer** [comment]
This is a strange issue and solution for it is even more surprising. 
In my case adding `level: 'info'` to filter configuration in filter section of m6_web_log_bridge config resolved this issue.
